### ISSUE TITLE
# Issue: Create a Timer Component for Word Scramble Game

### ISSUE THREAD

**Issue by bijiyiqi2017** [bijiyiqi2017/dragon24#15]
**Description**: Implement a timer component to track the time taken to complete each round of the word scramble game.

## Requirements:

1. **Functionality**: 
   - The timer should count down the time available to complete a round (e.g., 1 minute).

2. **Display**: 
   - The timer should be displayed in the format of `MM:SS` in the UI.

3. **Starting and Stopping**: 
   - The timer should start automatically at the beginning of each round.
   - The timer should stop when the round is completed or when the time runs out.

4. **Resetting**: 
   - The timer should reset at the start of each new round.
   - Optionally, display the time taken for each round after it concludes.

5. **User Interaction (Optional)**:
   - **Pause Button**: Allow users to pause the timer if needed.
   - **Resume Button**: After pausing, users should be able to resume the timer.
   - **Reset Button**: Enable a manual reset if the user wants to restart the timer at any point.

6. **Styling**: 
   - Use vibrant colors and clear, large fonts for visibility.
   - Consider animations for when time is running low.

7. **Testing**:
   - Ensure the timer starts and stops correctly with each round.
   - Test the display format for real-time accuracy.
   - Validate the reset functionality.
   - Check edge cases, such as the timer reaching zero.

## Contributor Checklist

- [ ] **Fork the Repository**:
  - Click the "Fork" button at the top right of the repository page to create your own copy.

- [ ] **Star the Repository (Optional)**:
  - Click the "Star" button at the top right of the repository page.
  - **Benefits**:
    - Increases visibility of the repository.
    - Allows you to keep track of interesting projects.
    - Shows appreciation for the maintainers and the community.

- [ ] **Clone Your Fork**:
  - Open your terminal and run:
    ```bash
    git clone <your-fork-url>
    ```
  - Replace `<your-fork-url>` with the URL of your forked repository.

- [ ] **Navigate to the Project Directory**:
  - Change into the directory of the cloned repo:
    ```bash
    cd <repository-name>
    ```

- [ ] **Create a New Branch**:
  - Create a new branch for your feature:
    ```bash
    git checkout -b timer-component
    ```

- [ ] **Implement the Timer Component**:
  - Follow the requirements outlined above to develop the timer.

- [ ] **Test Your Component**:
  - Ensure the timer functions correctly (start, stop, reset).
  - Verify that the display format is accurate.

- [ ] **Commit Your Changes**:
  - Stage your changes:
    ```bash
    git add .
    ```
  - Commit with a clear message:
    ```bash
    git commit -m "Add timer component for word scramble game"
    ```

- [ ] **Push to Your Fork**:
  - Push your branch to your forked repository:
    ```bash
    git push origin timer-component
    ```

- [ ] **Create a Pull Request**:
  - Go to your forked repository on GitHub and click "New Pull Request".
  - Compare your branch with the original repository’s main branch.
  - Provide a detailed description of your changes and submit the pull request.

## Screenshot Request
- Please include a screenshot of the timer component working in your local environment. Ensure it shows:
  - The timer is visible and correctly formatted.
  - It functioning (starting and stopping) during a mock round.

## Note for Contributors:
This issue is primarily aimed at contributors who have not submitted any pull requests during Hacktober Fest 2024. We want to encourage a diverse group of participants! If this issue remains open after October, previous contributors are also welcome to participate, as we aim to offer as many people as possible the opportunity to contribute to this challenge.

**Comment by mrhat05** [comment]
can i work on this?

**Comment by bijiyiqi2017** [comment]
Yes, you are welcome to contribute. If you have any questions please feel free to ask.

**Comment by bijiyiqi2017** [comment]
The second input field can/needs to be removed. If you can take care of that it would be greatly appreciated.

**Comment by mrhat05** [comment]
@bijiyiqi2017 
Hi, I hope you find this well! I’ve added a timer component to the scrambled word game in my pull request. Thanks for reviewing!
